# Generated by Django 4.0.7 on 2022-09-09 05:35

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('signup_time', models.DateTimeField(auto_now=True)),
                ('last_login', models.DateTimeField(auto_now=True)),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=30)),
                ('available_workout_days', models.CharField(max_length=10)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExerciseHistory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('exercise_name', models.CharField(max_length=255)),
                ('reps_real', models.IntegerField(blank=True, null=True)),
                ('weight_real', models.IntegerField(blank=True, null=True)),
                ('rest_real', models.IntegerField(blank=True, null=True)),
                ('duration_real', models.IntegerField(blank=True, null=True)),
                ('reps_goal', models.IntegerField(blank=True, null=True)),
                ('weight_goal', models.IntegerField(blank=True, null=True)),
                ('rest_goal', models.IntegerField(blank=True, null=True)),
                ('duration_goal', models.IntegerField(blank=True, null=True)),
                ('adherence', models.DecimalField(decimal_places=1, default=Decimal('0'), max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Exercises',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('exercise_name', models.CharField(max_length=255)),
                ('target_muscle', models.CharField(max_length=255)),
                ('workout_type', models.CharField(max_length=255)),
                ('video_link', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('enter_by', models.CharField(max_length=5)),
                ('brand', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=30)),
                ('carbohydrates', models.DecimalField(decimal_places=2, max_digits=5)),
                ('proteins', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fats', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fibers', models.DecimalField(decimal_places=2, max_digits=5)),
                ('sodium', models.DecimalField(decimal_places=2, max_digits=5)),
                ('calories', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='ProgramType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('program_name', models.CharField(max_length=255)),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=30)),
                ('available_workout_days', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('question_name', models.CharField(max_length=255)),
                ('question_type', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Workouts',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('workout_type', models.CharField(max_length=255)),
                ('program_type_id', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorkoutHistory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('adherence', models.DecimalField(decimal_places=1, default=Decimal('0'), max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WorkoutEvalHistory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('workout_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.workouts')),
            ],
        ),
        migrations.CreateModel(
            name='SleepQuestion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(auto_now=True)),
                ('score', models.IntegerField(blank=True, null=True)),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.question')),
            ],
        ),
        migrations.CreateModel(
            name='SleepHistory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(auto_now=True)),
                ('score', models.IntegerField(blank=True, null=True)),
                ('sleep_question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.sleepquestion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProgramTypeUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.programtype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NutritionHistory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now=True)),
                ('carbohydrates_real', models.DecimalField(decimal_places=2, max_digits=5)),
                ('proteins_real', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fats_real', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fibers_real', models.DecimalField(decimal_places=2, max_digits=5)),
                ('sodium_real', models.DecimalField(decimal_places=2, max_digits=5)),
                ('calories_real', models.DecimalField(decimal_places=2, max_digits=5)),
                ('carbohydrates_goal', models.DecimalField(decimal_places=2, max_digits=5)),
                ('proteins_goal', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fats_goal', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fibers_goal', models.DecimalField(decimal_places=2, max_digits=5)),
                ('sodium_goal', models.DecimalField(decimal_places=2, max_digits=5)),
                ('calories_goal', models.DecimalField(decimal_places=2, max_digits=5)),
                ('adherence', models.DecimalField(decimal_places=1, default=Decimal('0'), max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NutritionalHistory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(auto_now=True)),
                ('carbohydrates_real', models.IntegerField(blank=True, null=True)),
                ('proteins_real', models.IntegerField(blank=True, null=True)),
                ('fats_real', models.IntegerField(blank=True, null=True)),
                ('fibers_real', models.IntegerField(blank=True, null=True)),
                ('sodium_real', models.IntegerField(blank=True, null=True)),
                ('calories_real', models.IntegerField(blank=True, null=True)),
                ('proteins_goal', models.IntegerField(blank=True, null=True)),
                ('fats_goal', models.IntegerField(blank=True, null=True)),
                ('fibers_goal', models.IntegerField(blank=True, null=True)),
                ('sodium_goal', models.IntegerField(blank=True, null=True)),
                ('calories_goal', models.IntegerField(blank=True, null=True)),
                ('carbohydrates_goal', models.IntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ingestion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now=True)),
                ('meal_number', models.PositiveSmallIntegerField()),
                ('value', models.DecimalField(decimal_places=2, max_digits=5)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FoodIngestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.food')),
                ('ingestion_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ingestion')),
            ],
        ),
        migrations.CreateModel(
            name='ExerciseWorkoutHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise_history_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.exercisehistory')),
                ('workout_history_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.workouthistory')),
            ],
        ),
        migrations.CreateModel(
            name='EvaluationQuestion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(auto_now=True)),
                ('score', models.IntegerField(blank=True, null=True)),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.question')),
            ],
        ),
        migrations.CreateModel(
            name='AntrhopometricHistory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(auto_now=True)),
                ('height', models.FloatField()),
                ('weight', models.FloatField()),
                ('neck', models.FloatField()),
                ('waist', models.FloatField()),
                ('hip', models.FloatField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
